version: '3'

services:
  docs:
    image: form_builder_local_docs
    container_name: form_builder_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./form_builder:/app/form_builder:z
    ports:
      - '9000:9000'
    command: /start-docs
