version: '3'

volumes:
  form_builder_local_postgres_data: {}
  form_builder_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: form_builder_local_django
    container_name: form_builder_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: form_builder_production_postgres
    container_name: form_builder_local_postgres
    volumes:
      - form_builder_local_postgres_data:/var/lib/postgresql/data
      - form_builder_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
