# Generated by Django 5.0.10 on 2024-12-12 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='form_title_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250, verbose_name='Question Text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('help_text', models.CharField(blank=True, max_length=250, verbose_name='Help text')),
                ('type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('EMAIL', 'Email'), ('NUMBER', 'Number')], max_length=50, verbose_name='Type')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Length')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Minimum Value')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Maximum Value')),
                ('is_decimal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Decimal')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quera_forms.form', verbose_name='Form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quera_forms.question', verbose_name='Question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='question_type_idx'),
        ),
    ]
