# Generated by Django 5.0.10 on 2024-12-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='Question Text')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='Help text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('EMAIL', 'Email'), ('NUMBER', 'Number')], max_length=50, verbose_name='Type')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Length')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Minimum Value')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Maximum Value')),
                ('is_decimal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Decimal')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quera_forms.form', verbose_name='Form')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=250, verbose_name='User Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quera_forms.form', verbose_name='Form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Answer Text')),
                ('answer_number', models.FloatField(blank=True, null=True, verbose_name='Answer Number')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quera_forms.question', verbose_name='Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quera_forms.response', verbose_name='User Response')),
            ],
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['title'], name='form_title_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['user_identifier'], name='user_identifier_idx'),
        ),
    ]
