# Generated by Django 5.0.10 on 2024-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quera_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=300, verbose_name='Question Text'),
        ),
    ]
